/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BarrelTest */

#ifndef _Included_BarrelTest
#define _Included_BarrelTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BarrelTest
 * Method:    readRawData
 * Signature: (Ljava/lang/String;JJJILjava/nio/ByteBuffer;)I
 */
JNIEXPORT int JNICALL Java_BarrelTest_readRawData
  (JNIEnv *, jobject, jstring, jlong, jlong, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
