#!/bin/bash
set -e

if [ $# -lt 1 ]
  then
  echo "Usage: ${0} <version>"
  exit 1
fi

read -p "Make sure you committed all your changes. You should only release from master. Continue (N/y)? " -n 1 -r
echo

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "exiting..."
    exit 1
fi

VERSION=${1}

echo $VERSION > version

sbt clean publish
git add version
git commit -m "released version $VERSION"
git tag -a $VERSION -m "released $VERSION"
git push origin $VERSION
git push origin scala
